#!/usr/bin/env python3
"""Generate Terraform tfvars files for different environments"""

import json
import os
from pathlib import Path

DEVELOPMENT_CONFIG = {
    "gcp_project_id": "family-kitchen-dev",
    "environment": "development",
    "region": "us-central1",
    "app_name": "family-kitchen",
    "cloud_run_memory": "512Mi",
    "cloud_run_cpu": "1",
    "enabled_apis": [
        "firestore.googleapis.com",
        "run.googleapis.com",
        "secretmanager.googleapis.com",
        "logging.googleapis.com",
        "compute.googleapis.com",
        "artifactregistry.googleapis.com",
        "cloudresourcemanager.googleapis.com",
        "container.googleapis.com",
    ],
}

STAGING_CONFIG = {
    "gcp_project_id": "family-kitchen-staging",
    "environment": "staging",
    "region": "us-central1",
    "app_name": "family-kitchen",
    "cloud_run_memory": "1Gi",
    "cloud_run_cpu": "2",
    "enabled_apis": DEVELOPMENT_CONFIG["enabled_apis"],
}

PRODUCTION_CONFIG = {
    "gcp_project_id": "family-kitchen-prod",
    "environment": "production",
    "region": "us-central1",
    "app_name": "family-kitchen",
    "cloud_run_memory": "2Gi",
    "cloud_run_cpu": "4",
    "enabled_apis": DEVELOPMENT_CONFIG["enabled_apis"],
}


def generate_tfvars(config: dict, output_file: str) -> None:
    """Generate .tfvars file from config"""
    content = f'''# Generated Terraform variables for {config['environment']}
# Generated by: infra/generate_terraform_files.py

gcp_project_id    = "{config['gcp_project_id']}"
environment       = "{config['environment']}"
region            = "{config['region']}"
app_name          = "{config['app_name']}"
cloud_run_memory  = "{config['cloud_run_memory']}"
cloud_run_cpu     = "{config['cloud_run_cpu']}"

enabled_apis = [
'''
    for api in config["enabled_apis"]:
        content += f'  "{api}",\n'
    content += "]"

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    print(f"✅ Generated {output_file}")


if __name__ == "__main__":
    script_dir = Path(__file__).parent

    generate_tfvars(DEVELOPMENT_CONFIG, f"{script_dir}/environments/dev.tfvars")
    generate_tfvars(STAGING_CONFIG, f"{script_dir}/environments/staging.tfvars")
    generate_tfvars(PRODUCTION_CONFIG, f"{script_dir}/environments/prod.tfvars")

    print("\n✅ All .tfvars files generated successfully!")
